#ifndef ADVENT_OF_CODE_CPP_UTILS_COMMON_HPP
#define ADVENT_OF_CODE_CPP_UTILS_COMMON_HPP

#include <common/common.hpp>

#define ADVENT_OF_CODE_CPP_UTILS_NAMESPACE_NAME  utils
#define ADVENT_OF_CODE_CPP_UTILS_NAMESPACE       ADVENT_OF_CODE_CPP_NAMESPACE::ADVENT_OF_CODE_CPP_UTILS_NAMESPACE_NAME
#define ADVENT_OF_CODE_CPP_UTILS_NAMESPACE_BEGIN namespace ADVENT_OF_CODE_CPP_UTILS_NAMESPACE {
#define ADVENT_OF_CODE_CPP_UTILS_NAMESPACE_END   }

#endif  // ADVENT_OF_CODE_CPP_UTILS_COMMON_HPP
