#ifndef ADVENT_OF_CODE_CPP_COMMON_COMMON_HPP
#define ADVENT_OF_CODE_CPP_COMMON_COMMON_HPP

#define ADVENT_OF_CODE_CPP_NAMESPACE       advent_of_code_cpp
#define ADVENT_OF_CODE_CPP_NAMESPACE_BEGIN namespace ADVENT_OF_CODE_CPP_NAMESPACE {
#define ADVENT_OF_CODE_CPP_NAMESPACE_END   }

#define ADVENT_OF_CODE_CPP_ALWAYS_INLINE inline __attribute__((always_inline))

#endif  // ADVENT_OF_CODE_CPP_COMMON_COMMON_HPP
